project:
  type: website
  output-dir: _site

website:
  title: "Bootcamp Data Engineering – From Zero to Hero"
  description: "Programme Data Engineering — Débutant → Intermédiaire → Avancé"
  site-url: "https://diakite-data.github.io/data-engineering-bootcamp"
  repo-url: "git@github.com:diakite-data/data-engineering-bootcamp.git"
  repo-actions: [source, issue]

  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd

      - section: "Débutant"
        contents:
          - 01_intro_data_engineering.ipynb
          - 02_bash_for_data_engineers.ipynb
          - 03_git_for_data_engineers.ipynb
          - 04_python_basics_for_data_engineers.ipynb
          - 05_python_data_processing_for_data_engineers.ipynb
          - 06_intro_relational_databases.ipynb
          - 07_sql_for_data_engineers.ipynb
          - 08_intro_big_data_distributed.ipynb
          - 09_mongodb_for_data_engineers.ipynb
          - 10_elasticsearch_for_data_engineers.ipynb
          - 11_pyspark_for_data_engineering.ipynb
          - 12_orchestration_pipelines.ipynb
          - 13_BONUS_fastapi_for_data_engineers.ipynb

  navbar:
    right:
      - icon: github
        href: https://github.com/diakite-data/data-engineering-bootcamp

comments:
  giscus:
    repo: "diakite-data/data-engineering-bootcamp"
    repo-id: "R_kgDOQjHMsg"
    category: "General"
    category-id: "DIC_kwDOQjHMss4CzeOO"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    language: "fr"

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    code-fold: true
    highlight-style: dracula
    search: true
